#!/usr/bin/env bash
# Bash script that displays:
# To infinity and beyond indefinitely
# With a sleep 2 in between each iteration
# I am invincible!!! when receiving a SIGTERM signal

i=1

trigger_sigterm() {
	echo "I am invincible!!!";
}

trap "trigger_sigterm" SIGTERM

while ((i))
do
	echo "To infinity and beyond"
	sleep 2
done
